import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <div className='h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-14 mb-5 bg-red-500 border-4 border-black flex justify-center items-center'>
          <span className='text-2xl'>
            S2 level
          </span>
      </div>
      <div className='mt-20 h-1/2 flex flex-col justify-between'>
        <Link href='/beginner'>
          <a className='h-20  bg-green-500 border-4 border-black rounded-lg flex justify-center items-center'>
            <span className='text-2xl'>
              (Guided) Tutorial
            </span>
          </a>
        </Link>
        <Link href='/advanced'>
          <a className='h-20  bg-blue-500 border-4 border-black rounded-lg flex justify-center items-center'>
            <span className='text-2xl'>
              I want to build it myself!
            </span>
          </a>
        </Link>
      </div>
    </div>
  )
}
